{
 "title": "Filter Page",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "All Machines",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    f.name AS factory_name,\n    sm.name AS system_name,\n    s.status AS system_status,\n    em.name AS expansion_name,\n    e.status AS expansion_status,\n    senm.name AS sensor_name,\n    se.status AS sensor_status\nFROM\n    factory f\nJOIN\n    system s ON f.id = s.factory_id\nJOIN\n    system_model sm ON s.system_model_id = sm.id\nJOIN\n    expansion e ON s.id = e.system_id\nJOIN\n    expansion_model em ON e.expansion_model_id = em.id\nJOIN\n    sensor se ON e.id = se.expansion_id\nJOIN\n    sensor_model senm ON se.sensor_model_id = senm.id;\n"
    }
   ]
  },
  {
   "title": "Task Duration Statistics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sm.name AS system_name,\n  MAX(t.duration) AS max_duration,\n  MIN(t.duration) AS min_duration,\n  AVG(EXTRACT(EPOCH FROM t.duration)) AS avg_duration_seconds\nFROM system_model sm\nJOIN system s ON sm.id = s.system_model_id\nJOIN task t ON s.id = t.system_id\nGROUP BY sm.name;\n"
    }
   ]
  },
  {
   "title": "Distribution of expansions per Factory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT f.name AS factory_name, COUNT(e.id) AS num_expansions\nFROM factory f\nJOIN system s ON f.id = s.factory_id\nJOIN expansion e ON s.id = e.system_id\nGROUP BY f.name\nORDER BY num_expansions DESC;\n"
    }
   ]
  },
  {
   "title": "Average Energetic Costs of Tasks by System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT sm.name AS system_name, AVG(t.energetic_costs) AS avg_energetic_costs\nFROM system_model sm\nJOIN system s ON sm.id = s.system_model_id\nJOIN task t ON s.id = t.system_id\nGROUP BY sm.name\nORDER BY avg_energetic_costs DESC;\n"
    }
   ]
  },
  {
   "title": "Number of Systems by Factory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT f.name AS factory_name, COUNT(s.id) AS num_systems\nFROM factory f\nJOIN system s ON f.id = s.factory_id\nGROUP BY f.name\nORDER BY num_systems DESC;\n"
    }
   ]
  },
  {
   "title": "Sensors by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT senm.type AS sensor_type, COUNT(se.id) AS num_sensors\nFROM sensor_model senm\nJOIN sensor se ON senm.id = se.sensor_model_id\nGROUP BY senm.type;\n"
    }
   ]
  }
 ]
}