{
 "title": "General View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "factory_name", "label": "Factory Name", "query": "select name from factory" },
   {
    "name": "factory_id",
    "label": "Factory ID",
    "query": "select id from factory where name IN ($factory_name)"
   },
   {
    "name": "system_id",
    "query": "select s.id from system_model sm\ninner join system s on sm.id = s.system_model_id\ninner join factory f on f.id = s.factory_id\nwhere f.name in ($factory_name)"
   },
   {
    "name": "status",
    "label": "System Status",
    "query": "Offline, Online, Working, Maintenance Required"
   }
  ]
 },
 "panels": [
  { "title": "General View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    factory.name,\r\n    factory.tag,\r\n    factory.location,\r\n    factory.longitude,\r\n    factory.latitude,\r\n    COUNT(system.id) AS total_systems\r\nFROM factory\r\nINNER JOIN system ON factory.id = system.factory_id\r\nWHERE factory.id IN ($factory_id)\r\nGROUP BY factory.name, factory.tag, factory.longitude, factory.latitude, factory.location;\r\n"
    }
   ]
  },
  {
   "title": "System Status v1",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n    COUNT(*) AS total_systems,\r\n    SUM(CASE WHEN system.status = 'Working' OR system.status = 'Online' THEN 1 ELSE 0 END) AS systems_working_or_online\r\nFROM factory\r\nINNER JOIN system ON factory.id = system.factory_id\r\nWHERE factory.id IN ($factory_id);\r\n\r\n"
    }
   ]
  },
  {
   "title": "System Status v2",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN system.status = 'Online' THEN 1 ELSE 0 END) AS \"Systems Online\",\r\n    SUM(CASE WHEN system.status = 'Working' THEN 1 ELSE 0 END) AS \"Systems Working\",\r\n    SUM(CASE WHEN system.status = 'Maintenance Required' THEN 1 ELSE 0 END) AS \"Systems Requiring Maintenance\",\r\n    SUM(CASE WHEN system.status = 'Offline' THEN 1 ELSE 0 END) AS \"Systems Offline\"\r\nFROM factory\r\nINNER JOIN system ON factory.id = system.factory_id\r\nWHERE factory.id IN ($factory_id);\r\n\r\n"
    }
   ]
  },
  {
   "title": "Active Facilities",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select Count(*) from factory where id IN ( $factory_id  )"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN system.status = 'Online' THEN 1 ELSE 0 END) AS \"Systems Online\",\r\n    SUM(CASE WHEN system.status = 'Working' THEN 1 ELSE 0 END) AS \"Systems Working\",\r\n    SUM(CASE WHEN system.status = 'Maintenance Required' THEN 1 ELSE 0 END) AS \"Systems Requiring Maintenance\",\r\n    SUM(CASE WHEN system.status = 'Offline' THEN 1 ELSE 0 END) AS \"Systems Offline\"\r\nFROM factory\r\nINNER JOIN system ON factory.id = system.factory_id\r\nWHERE factory.id IN ($factory_id);\r\n\r\n"
    }
   ]
  },
  { "title": "Factory: $factory_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "factory_name" },
  {
   "title": "Systems",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "\r\n\r\nSELECT\r\n    s.id AS \"ID\",\r\n    sm.name AS \"Name\",\r\n    sm.type AS \"Type\",\r\n    sm.manufacturer AS \"Manufacturer\",\r\n    s.status AS \"Status\"\r\nFROM system AS s\r\nINNER JOIN system_model AS sm ON s.system_model_id = sm.id\r\nINNER JOIN factory AS f ON s.factory_id = f.id\r\nWHERE f.name IN ($factory_name);\r\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN system.status = 'Online' THEN 1 ELSE 0 END) AS \"Systems Online\",\r\n    SUM(CASE WHEN system.status = 'Working' THEN 1 ELSE 0 END) AS \"Systems Working\",\r\n    SUM(CASE WHEN system.status = 'Maintenance Required' THEN 1 ELSE 0 END) AS \"Systems Requiring Maintenance\",\r\n    SUM(CASE WHEN system.status = 'Offline' THEN 1 ELSE 0 END) AS \"Systems Offline\"\r\nFROM factory\r\nINNER JOIN system ON factory.id = system.factory_id\r\nWHERE factory.name IN ($factory_name);\r\n\r\n"
    }
   ]
  }
 ]
}