{
 "title": "Systems View",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "factory_name", "label": "Factory Name", "query": "select name from factory" },
   {
    "name": "factory_id",
    "label": "Factory ID",
    "query": "select id from factory where name in ('${factory_name:text}')"
   },
   {
    "name": "system_id",
    "label": "System",
    "query": "select s.id from system s\ninner join factory f on f.id = s.factory_id\nwhere f.id = $factory_id"
   },
   {
    "name": "system_model_name",
    "label": "System Name",
    "query": "select name from system_model sm\ninner join system s on s.system_model_id = sm.id\nwhere s.id = $system_id"
   },
   {
    "name": "expansion_id",
    "label": "Expansion ID",
    "query": "select e.id from expansion e\ninner join system s on s.id = e.system_id\nwhere s.id = $system_id"
   },
   {
    "name": "sensor_id",
    "label": "Sensor ID",
    "query": "select id from sensor where expansion_id in ($expansion_id)"
   }
  ]
 },
 "panels": [
  { "title": "System View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select status from system s where id = $system_id "
    }
   ]
  },
  {
   "title": "System Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT 'Name' AS \"Key\", sm.name::text AS \"Value\" FROM system s\r\nINNER JOIN system_model sm ON sm.id = s.system_model_id\r\nWHERE s.id = $system_id\r\n\r\nUNION ALL\r\n\r\nSELECT 'Manufacturer' AS \"Key\", sm.manufacturer::text AS \"Value\" FROM system s\r\nINNER JOIN system_model sm ON sm.id = s.system_model_id\r\nWHERE s.id = $system_id\r\n\r\nUNION ALL\r\n\r\nSELECT 'Type' AS \"Key\", sm.type::text AS \"Value\" FROM system s\r\nINNER JOIN system_model sm ON sm.id = s.system_model_id\r\nWHERE s.id = $system_id\r\n\r\nUNION ALL\r\n\r\nSELECT 'Expansions' AS \"Key\", COUNT(e.id)::text AS \"Value\" FROM system s\r\nLEFT JOIN expansion e ON e.system_id = s.id\r\nWHERE s.id = $system_id;\r\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN expansion.status = 'Online' THEN 1 ELSE 0 END) AS \"Expansions Online\",\r\n    SUM(CASE WHEN expansion.status = 'Working' THEN 1 ELSE 0 END) AS \"Expansions Working\",\r\n    SUM(CASE WHEN expansion.status = 'Maintenance Required' THEN 1 ELSE 0 END) AS \"Expansions Requiring Maintenance\",\r\n    SUM(CASE WHEN expansion.status = 'Offline' THEN 1 ELSE 0 END) AS \"Expansions Offline\"\r\nFROM system\r\nINNER JOIN expansion ON system.id = expansion.system_id\r\nWHERE system.id = $system_id \r\n\r\n"
    }
   ]
  },
  {
   "title": "Status Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp AS \"time\",\r\n    s.id AS \"sensor_id\",\r\n    s.status AS \"sensor_status\"\r\nFROM\r\n    sensor s\r\nJOIN\r\n    expansion e ON s.expansion_id = e.id\r\nJOIN\r\n    system sys ON e.system_id = sys.id\r\nJOIN\r\n    factory f ON sys.factory_id = f.id\r\nWHERE\r\n    timestamp >= $__timeFrom() AND timestamp <= $__timeTo()\r\n"
    }
   ]
  },
  {
   "title": "Task Schedule",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    time_series AS \"time\",\r\n    CASE\r\n        WHEN random() < 0.4 THEN (\r\n            SELECT 'T1 - ' || name FROM task WHERE system_id = $system_id ORDER BY id ASC LIMIT 1\r\n        )\r\n        WHEN random() >= 0.4 AND random() < 0.8 THEN (\r\n            SELECT 'T2 - ' || name FROM task WHERE system_id = $system_id ORDER BY id DESC LIMIT 1\r\n        )\r\n        ELSE null\r\n    END AS \"$system_model_name\"\r\nFROM\r\n    generate_series(\r\n        $__timeFrom()::timestamp,\r\n        $__timeTo()::timestamp,\r\n        '10 min'::interval\r\n    ) AS time_series;\r\n"
    }
   ]
  },
  { "title": "Expansion $expansion_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "expansion_id" },
  {
   "title": "Expansion",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT 'Name' AS \"Key\", em.name::text AS \"Value\" FROM expansion e\r\nINNER JOIN expansion_model em ON em.id = e.expansion_model_id\r\nWHERE e.id in ($expansion_id)\r\n\r\nUNION ALL\r\n\r\nSELECT 'Manufacturer' AS \"Key\", em.manufacturer::text AS \"Value\" FROM expansion e\r\nINNER JOIN expansion_model em ON em.id = e.expansion_model_id\r\nWHERE e.id in ($expansion_id)\r\n\r\nUNION ALL\r\n\r\nSELECT 'Type' AS \"Key\", em.type::text AS \"Value\" FROM expansion e\r\nINNER JOIN expansion_model em ON em.id = e.expansion_model_id\r\nWHERE e.id in ($expansion_id)\r\n\r\nUNION ALL\r\n\r\nSELECT 'Sensors' AS \"Key\", COUNT(s.id)::text AS \"Value\" FROM sensor s\r\nWHERE s.expansion_id in ($expansion_id);\r\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "current_value{sensor_id=\"$expansion_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 5, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "current_value{sensor_id=\"$expansion_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "current_value{sensor_id=\"$expansion_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 22 },
   "targets": [
    {
     "expr": "current_value{sensor_id=\"$expansion_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}