version: '3'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - monitoring-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:10.1.4
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=volkovlabs-echarts-panel
    depends_on:
      - postgres
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.pg
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "4321:80"
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring-network
    
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - monitoring-network
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
      - ./config:/mosquitto/config:rw
    restart: unless-stopped
  
  dinasore:
    image: dinasore:latest
    container_name: dinasore
    environment:
      - DINASORE_4DIAC_PORT=61499 
      - DINASORE_OPCUA_PORT=4840 
    ports:
      - "61499:61499" 
      - "4840:4840"  
    networks:
      - monitoring-network
    volumes:
      - dinasore-data:/var/lib/dinasore/data
    restart: unless-stopped

  dinasore_1:
    build: ./dinasore
    container_name: dinasore_1
    command: python -B core/main.py -p 61499 -u 4840 -a dinasore_1
    ports:
      - "61499:61499" 
      - "4840:4840"  
    networks:
      - monitoring-network
    volumes:
      - dinasore1-data:/var/lib/dinasore/data
    restart: unless-stopped

  dinasore_2:
    build: ./dinasore
    container_name: dinasore_2
    command: python -B core/main.py -p 61500 -u 4841 -a dinasore_2
    ports:
      - "61500:61500" 
      - "4841:4841"  
    networks:
      - monitoring-network
    volumes:
      - dinasore2-data:/var/lib/dinasore/data
    restart: unless-stopped

networks:
  monitoring-network:
    driver: bridge

volumes:
  postgres-data:
  prometheus-config:
  prometheus-data:
  grafana-data:
  mosquitto-data:
  mosquitto-logs:
  dinasore1-data:
  dinasore2-data:
  config: